version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8001:8000
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pg_db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u msg_broker_conn.py'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pg_db

  pg_db:
    container_name: pg_db
    image: postgis/postgis:13-3.1-alpine
    restart: unless-stopped
    volumes:
      - pg-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGDATA:/var/lib/postgresql/data
    ports:
      - '5435:5432'

volumes:
  pg-db:
    driver: local