pipeline {
    agent any
    stages {
         stage('Setup user_auth microservice'){
            steps {
                sh '''
                    git clone https://github.com/shoumitro-cse/django_microservice.git
                    chmod +x /var/lib/jenkins/workspace/ci_cd/django_microservice/ci_cd_pipe_line/user_auth/venv_setup.sh
                    /var/lib/jenkins/workspace/ci_cd/django_microservice/ci_cd_pipe_line/user_auth/venv_setup.sh
                    
                    chmod +x /var/lib/jenkins/workspace/ci_cd/django_microservice/ci_cd_pipe_line/user_auth/gunicorn.sh
                    /var/lib/jenkins/workspace/ci_cd/django_microservice/ci_cd_pipe_line/user_auth/gunicorn.sh
                    
                    chmod +x /var/lib/jenkins/workspace/ci_cd/django_microservice/ci_cd_pipe_line/user_auth/nginx.sh
                    /var/lib/jenkins/workspace/ci_cd/django_microservice/ci_cd_pipe_line/user_auth/nginx.sh
                '''
            }
        }
        stage('Setup business microservice'){
            steps {
                sh '''
                    cd django_microservice/business
                    cp env.example .env
                    python -m venv venv
                    source ./venv/bin/activate
                    pip install -r requirements.txt
                    python manage.py makemigrations
                    python manage.py migrate
                    python manage.py collectstatic
                    rm -rf static
                    mv staticfiles static
                    python manage.py runserver localhost:7000
                '''
            }
        }
    }
}
